disabled_rules:
- trailing_whitespace
- identifier_name
- compiler_protocol_init
- unused_optional_binding
- force_cast
- force_try
- type_name
- large_tuple
opt_in_rules:
- empty_count
- empty_string
included:
  - Vocable
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 250
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 500
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
nesting:
    type_level: 5
reporter: "xcode"
